### ISSUE TITLE
Nice work!

### ISSUE THREAD

**Issue by Mxrcon** [abhi18av/hello_nf#1]
Hey! That's a very nice implementation of the hello word, I used processes on my version, but using bin seems to be easier and more readable! 

I've 1 question, If you add more languages, wouldn't this make the main docker image too big? or the docker image size is manageable?

Nice work! 
Davi

**Comment by abhi18av** [comment]
Hi @Mxrcon, 

Actually, I created this example for someone at work, who was having trouble with Docker container creation and usage. 

I'm happy to see that you were able to pick upon something from this toy implementation 😊 

Thanks,
Abhinav

P.S. I'll be closing this issue, we can continue the discussion whenver we connect next.

**Comment by abhi18av** [comment]
> I've 1 question, If you add more languages, wouldn't this make the main docker image too big? or the docker image size is manageable? 

Exactly, I personally would avoid taking the approach of big custom docker containers and rely upon `biocontainers` or atleast `conda` to create the custom image.

**Comment by Mxrcon** [comment]
Yes! i understand, and maybe the docker hub ones would fit on this task! I'm very interested on docker right now, we could discuss on our next meeting, I'm using the time between tower runs to read about it.
